language: python
python:
  - "3.6"
dist: bionic
sudo: true

services:
  - postgresql

addons:
  postgresql: "10.9"
  apt:
    packages:
      - postgresql-10.9
      - postgresql-client-10.9

env:
  global:
    - PGPORT=5433

install:
  - pip install -r requirements.txt

before_script:
  - sudo -i -u postgres psql -c 'create database active_type_test;'

script:
  - chmod u+x run_server.sh
  - ./run_server.sh

branches:
  only:
    - andrei-dev