language: python
python:
  - "3.6"
dist: bionic
sudo: false

addons:
  apt:
    packages:
      - git

services:
  - postgresql # version 10.9

install:
  - pip install -r requirements.txt

before_script:
  - psql -U postgres postgres -f create_db.sql

script:
  - chmod u+x run_server.sh
  - ./run_server.sh

branches:
  only:
    - andrei-dev