language: python
python:
  - "3.6"
dist: bionic
sudo: true

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGPORT=5433

install:
  - pip install -r requirements.txt

before_script:
  - sudo /etc/init.d/postgresql start 10
  - sudo service postgresql status 10
  - sudo psql --version
  - sudo -i -u postgres psql -h localhost -p 5433 -a -c 'create database active_type_test;'

script:
  - chmod u+x run_server.sh
  - ./run_server.sh

branches:
  only:
    - andrei-dev