# Generated by Django 2.2 on 2019-08-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_set', to='plannerapp.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
