# Generated by Django 2.2 on 2019-08-26 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_auto_20190826_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participation_set', to='plannerapp.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_participation_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
