# Generated by Django 2.0.13 on 2019-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0004_auto_20190715_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='project_thumbnails', verbose_name='Превью'),
        ),
    ]
