# Generated by Django 2.0.13 on 2019-07-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0005_auto_20190718_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичность'),
        ),
    ]
