# Generated by Django 2.0.13 on 2019-07-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0007_auto_20190723_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(related_name='categories', to='plannerapp.Project'),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plannerapp.Category', verbose_name='category'),
        ),
    ]
