# Generated by Django 2.0.13 on 2019-07-27 16:42

from django.db import migrations, models
import django.db.models.deletion
import functools
import plannerapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0009_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=functools.partial(plannerapp.models.get_default_category_pk, *(), **{'name': 'TO-DO'}), null=True, on_delete=django.db.models.deletion.SET_NULL, to='plannerapp.Category', verbose_name='category'),
        ),
    ]
