"""
Django settings for GeekPlanner project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = 'm-$8#^xgw-ctn!bah#2jw!!2=_%@b(kof#$-@7-_p0@e8zd9!8'

# ============================================================================
# Debug settings
# ============================================================================
DEBUG = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
DATA_DIR = os.path.join(BASE_DIR, 'testing_data')

# ============================================================================
# Hosts & Domains
# ============================================================================
ALLOWED_HOSTS = ['*']
DOMAIN_NAME = 'http://localhost:8000'

# ============================================================================
# Application definition
# ============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'authapp',
    'plannerapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GeekPlanner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GeekPlanner.wsgi.application'

# ============================================================================
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'geekplanner',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# ============================================================================
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
# ============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================================
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# ============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ============================================================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# ============================================================================
# Root URL for static content
STATIC_URL = '/static/'
# Directories for static content
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
# URL for media content: 127.0.0.1:8000/media/
MEDIA_URL = '/media/'
# Project root directory of media content
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Project thumbnails are stored in the /media/project_thumbnails/ directory
PROJECT_THUMBNAIL_DIR = 'project_thumbnails'
# User avatars are stored in the /media/user_avatars/ directory
USER_AVATARS_DIR = 'user_avatars'

# ============================================================================
# Email
# ============================================================================
EMAIL_HOST = 'localhost'
EMAIL_PORT = '1025'
EMAIL_HOST_USER = 'admin@geekplanner.local'
EMAIL_HOST_PASSWORD = 'admin'
EMAIL_USE_SSL = False
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = 'tmp/emails/'

# ============================================================================
# Authentication
# ============================================================================
# List of backends used for user authentication
AUTHENTICATION_BACKENDS = (
    ('django.contrib.auth.backends.ModelBackend',)
)
# Model which we use for authentication
AUTH_USER_MODEL = 'authapp.User'
